framework:
    validation:
        enabled: true 
        enable_attributes: true
        # auto_mapping permet à Symfony de deviner certaines contraintes
        # à partir des métadonnées Doctrine si tu veux l'activer plus tard.
        # auto_mapping:
        #     App\Entity\: []

when@test:
    framework:
        validation:
            not_compromised_password: false

